### PR TITLE
Do not remove released pin from known pins

### PR DESCRIPTION
**Pull request by bezineb5**
This is a fix for issue #74 
Once the pin is removed from the list of known pins, it cannot be reused.
However this removal was clearly intentional, and I don't know why. Am I missing something?

### CODE REVIEW

**Comment by penfold42** [comment]
I tend to agree with this new approach

**Comment by sarfata** [comment]
Yeah I agree too. `known_pins` should be constant once we are done parsing the arguments. Not sure why we have that here (I don't remember), most likely a mistake.

Can one of you just confirm that you have tested? I don't have the hardware handy to make sure things still work after the change. Just a quick test setting and releasing all the pins twice would be great I think. 

And then me or @penfold42 can merge this. Thanks @bezineb5!

**Comment by bezineb5** [comment]
I just tested multiple releases and it stops working after 2/3 releases. There's no error log but I'll investigate. Do not merge this PR!

**Comment by bezineb5** [comment]
I updated my PR and it seems to be working fine after multiple release commands. The new changes are:
* When compacting the array of active pins, the end of the array was left uninitialized
* update_pwm() was called even when no pin was updated or released

**Comment by sarfata** [comment]
Looks good to me but could you increase the version number before we merge this?

https://github.com/sarfata/pi-blaster/blob/5c38ab15aaa491c513f1adeab525a171926e110d/configure.ac#L5

I think 0.1.3 would be good since this should not be a breaking change.

**Comment by bezineb5** [comment]
Done

**Comment by sarfata** [comment]
thanks @bezineb5 !

**Pull request merged**
