### PR TITLE
Added rpi3 support, added more gpios

### PR DESCRIPTION
**Pull request by penfold42**
and also fixed up the pin2gpio allocation - 16 is the max now

### CODE REVIEW

**Comment by sarfata** [comment]
Nice. Thanks a lot for taking care of this. I will give it a quick try tonight and will merge it afterwards!

**Comment by sarfata** [comment]
Can you add your name to the list of contributors in the README? (only if you want to of course)

**Comment by penfold42** [comment]
I'll update the contributors in my next pull request.

Have you seen my dynamic-gpio fork ?
It lets you specify the gpio pins on the command line (but defaults to the hard coded list in the source)

**Comment by sarfata** [comment]
Tested. Works great. Thanks a lot.

This closes #59.

**Pull request merged**
