### PR TITLE
Multi-pin input and small fixes

### PR DESCRIPTION
**Pull request by pavlecc**
Feature: Multi-pin input (e.g. "2=0.2 3=0.5 17=1")
Fix: Releasing pin will remove it from known_pins array
Fix: Setting all pins to a value now works with all known pins

### CODE REVIEW

**Comment by sarfata** [comment]
@penfold42 do you have time to look at this? I could give you review/merge permissions since you have been pretty active on the questions and pull-requests. I have had little time to take care of pi-blaster recently.

**Comment by penfold42** [comment]
Yep - probably on the weekend.

Happy to help - I still have a 12 pin (4x rgb led) test rig handy

**Comment by penfold42** [comment]
@pavlecc
Should we more actively test the field separator for a specific character? Accepting comma or space would be good.

Have you tested with multiple consecutive field separators ?

Is it worth adding support for releasing multiple pins ?

**Comment by pavlecc** [comment]
@penfold42 
I haven't, I'm running this from another program, so I have it formatted properly all the time.
The string is:pin=floatvalue[space]pin=floatvalue[space]...pin=floatvalue[endofline]
I can try it out during the weekend and provide an update if needed.

Not sure about multipin release, though.. I've been releasing one during testing of my patch.. But in real-world example I can't really think of a usecase when you need to change pins that way :)

**Comment by pavlecc** [comment]
@penfold42, I've just checked. The current code can handle already commas or similar delimiters (, ; \t) and multiple spaces. It cannot handle multiple delimiters (several commas, or similar..). Also, it requires that \n goes straight after the last input, but I believe that's a fair rule.

An example of a string that works:
"1=0.5\t   2=0.9432,    17=0; 15=1.00\n"

**Comment by penfold42** [comment]
Thanks - I got distracted by other shiny things this weekend !

Can you add a commit to update the readne ?

When I get granted access I'll merge it

**Comment by sarfata** [comment]
@penfold42 I have sent you an invitation to have push access to this repo. Thanks!

**Comment by pavlecc** [comment]
Hello again, are there any updates on this? :) Thanks!

**Comment by penfold42** [comment]
thanks and sorry for the delay - I've finally got around to some testing and it looks good

**Pull request merged**
